export const playmatchs: Record<string, string> = {
  1: 'https://media.magic.wizards.com/images/wallpaper/sacred-foundry_sld_1920x1080_wallpaper.jpg',
  2: 'https://media.magic.wizards.com/images/wallpaper/grief_mh2_1920x1080_wallpaper.jpg',
  3: 'https://media.magic.wizards.com/images/wallpaper/quandrixcommand_stx_1920x1080_wallpaper.jpg',
  4: 'https://media.magic.wizards.com/images/wallpaper/thrill-of-possibility_ma_stx_1920x1080_wallpaper.jpg',
}

export const sleeveColors: Record<string, string> = {
  1: '#6b0f1a',
  2: '#ff4e00',
  3: '#2a2a72',
  4: '#5ca0f2',
}

export const playerNames: Record<string, string> = {
  1: 'Patrick Dias',
  2: 'Canter',
  3: 'iReshi',
  4: 'Lirandart',
}

export const sleeveColorGradients: Record<string, string> = {
  1: 'linear-gradient(315deg, #6b0f1a 0%, #b91372 74%)',
  2: 'linear-gradient(315deg, #ff4e00 0%, #ec9f05 74%)',
  3: 'linear-gradient(315deg, #2a2a72 0%, #009ffd 74%)',
  4: 'linear-gradient(315deg, #5ca0f2 0%, #f5f7f6 74%)',
}

export const decks: Record<string, string[]> = {
  '1': [
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
    '1 Kozilek, the Great Distortion',
    '1 Morophon, the Boundless',
    '1 Golos, Tireless Pilgrim',
    '1 Ulamog, the Ceaseless Hunger',
    '1 Emrakul, the Promised End',
    '1 Vela the Night-Clad',
    '1 The World Tree',
    '1 Introduction to Annihilation',
    '1 Reflections of Littjara',
  ],
  '2': [
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
    '1 Arbor Elf',
    '1 Argothian Elder',
    '1 Beastmaster Ascension',
    '1 Blanchwood Armor',
    '1 Bramblewood Paragon',
    '1 Coat of Arms',
    '1 Copperhorn Scout',
    '1 Devoted Druid',
    `1 Talara's Battalion`,
    '1 Wood Elves',
  ],
  '3': [
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
    '1 Sunscorch Regent',
    '1 Terror of the Peaks',
    '1 Wasitora, Nekoru Queen',
    '1 Amareth, the Lustrous',
    '1 Dragonlord Dromoka',
    '1 Hellkite Charger',
    '1 Hellkite Courser',
    '1 Intet, the Dreamer',
    '1 Keiga, the Tide Star',
  ],
  '4': [
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
    '1 Graveborn Muse',
    '1 Gravespawn Sovereign',
    '1 Gray Merchant of Asphodel',
    '1 Lord of the Accursed',
    '1 Lord of the Undead',
    '1 Midnight Reaper',
    '1 Murderous Rider',
    '1 Noxious Ghoul',
    '1 Relentless Dead',
  ],
}
